spring.application.name=atendimento-publico
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5435/atendimentodb
spring.datasource.username=atendimento
spring.datasource.password=atendimento
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
