-- Schema baseline da Instância 1 (Compliance Corporativo).
-- Materializa as entidades dos pontos fixos definidas no Core (br.imd.ufrn.core.domain).
-- Os nomes de coluna seguem o physical naming strategy do Hibernate (camelCase -> snake_case)
-- para que `spring.jpa.hibernate.ddl-auto=validate` passe na inicialização.

CREATE TABLE manifestations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    protocol_number VARCHAR(255) NOT NULL UNIQUE,
    title           VARCHAR(500) NOT NULL,
    description     TEXT         NOT NULL,
    type            VARCHAR(100) NOT NULL,
    status          VARCHAR(255) NOT NULL,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL,
    active          BOOLEAN      NOT NULL
);

CREATE TABLE audit_entries (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manifestation_id BIGINT       NOT NULL,
    actor_id         BIGINT       NOT NULL,
    action           VARCHAR(255) NOT NULL,
    description      TEXT,
    occurred_at      TIMESTAMP    NOT NULL
);

CREATE TABLE decision_records (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manifestation_id BIGINT       NOT NULL,
    author_id        BIGINT       NOT NULL,
    type             VARCHAR(255) NOT NULL,
    content          TEXT         NOT NULL,
    created_at       TIMESTAMP    NOT NULL,
    updated_at       TIMESTAMP    NOT NULL,
    active           BOOLEAN      NOT NULL
);

CREATE TABLE responsible_assignments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manifestation_id BIGINT    NOT NULL,
    responsible_id   BIGINT    NOT NULL,
    assigned_by_id   BIGINT,
    created_at       TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP NOT NULL,
    active           BOOLEAN   NOT NULL
);

CREATE TABLE service_evaluations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manifestation_id BIGINT    NOT NULL UNIQUE,
    rating           INTEGER   NOT NULL,
    comment          TEXT,
    created_at       TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP NOT NULL,
    active           BOOLEAN   NOT NULL
);
