-- Vínculo manifestação → usuário acusado (base do conflito de interesse por hierarquia/departamento).
-- Dado próprio da Instância 1.

CREATE TABLE manifestation_accusation (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manifestation_id BIGINT    NOT NULL REFERENCES manifestations (id),
    accused_user_id  BIGINT    NOT NULL REFERENCES user_info (id),
    created_at       TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP NOT NULL,
    active           BOOLEAN   NOT NULL
);
