-- Notificações da Instância 1 (dado próprio; o Core não modela notificação).
CREATE TABLE notification (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id BIGINT,
    manifestation_id  BIGINT       NOT NULL,
    type              VARCHAR(50)  NOT NULL,
    message           VARCHAR(500) NOT NULL,
    read_flag         BOOLEAN      NOT NULL,
    created_at        TIMESTAMP    NOT NULL,
    updated_at        TIMESTAMP    NOT NULL,
    active            BOOLEAN      NOT NULL
);
