-- Anexos (evidências) das manifestações; conteúdo binário guardado no banco.
CREATE TABLE attachment (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manifestation_id BIGINT       NOT NULL,
    file_name        VARCHAR(255) NOT NULL,
    content_type     VARCHAR(255),
    file_size        BIGINT       NOT NULL,
    content          BYTEA        NOT NULL,
    created_at       TIMESTAMP    NOT NULL,
    updated_at       TIMESTAMP    NOT NULL,
    active           BOOLEAN      NOT NULL
);
