-- Novo ponto fixo de infraestrutura do Core (br.imd.ufrn.core.domain.Party /
-- ManifestationAccusation), trazido pelo merge do origin/main. A Instância 1 continua usando sua
-- própria implementação (br.imd.ufrn.conflict.*, tabela manifestation_accusation) — ver TODO em
-- EgideApplication. Estas tabelas só existem para satisfazer o Hibernate ddl-auto=validate
-- (entidades escaneadas mesmo com repositório/controller do Core excluídos); ficam sem uso.
CREATE TABLE parties (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    unit       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    active     BOOLEAN      NOT NULL
);

CREATE TABLE manifestation_accusations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manifestation_id BIGINT NOT NULL,
    accused_party_id BIGINT NOT NULL,
    created_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP NOT NULL,
    active          BOOLEAN   NOT NULL
);
