-- A acusação (manifestação -> parte acusada) é um ponto fixo do Core
-- (br.imd.ufrn.core.domain.ManifestationAccusation), usado como insumo pela estratégia de
-- conflito de interesse (LegalConflictStrategy). Esta tabela não existia ainda na instância 3.

CREATE TABLE manifestation_accusations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manifestation_id  BIGINT    NOT NULL,
    accused_party_id  BIGINT    NOT NULL,
    created_at        TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP NOT NULL,
    active            BOOLEAN   NOT NULL DEFAULT TRUE
);
