-- Parte envolvida no fluxo de ouvidoria (br.imd.ufrn.core.domain.Party) é ponto fixo de
-- infraestrutura do Core, usada como insumo pela estratégia de conflito de interesse. Esta tabela
-- não existia ainda na instância 3.

CREATE TABLE parties (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    unit       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE
);
