-- Schema específico da Instância 2 para o ponto variável de conflito de interesse.
-- Tabelas próprias da ouvidoria universitária (não existem no Core): a unidade acadêmica de
-- cada membro e o vínculo manifestação -> denunciado.

CREATE TABLE academic_members (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    unit       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    active     BOOLEAN      NOT NULL
);

CREATE TABLE manifestation_accusations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manifestation_id  BIGINT    NOT NULL UNIQUE,
    accused_member_id BIGINT    NOT NULL,
    created_at        TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP NOT NULL,
    active            BOOLEAN   NOT NULL
);
