-- A acusação (manifestação -> parte acusada) passou a ser um ponto fixo do Core
-- (br.imd.ufrn.core.domain.ManifestationAccusation). Este migration alinha a tabela local ao
-- schema do Core: coluna `accused_party_id` (id opaco da parte) e sem restrição de unicidade em
-- manifestation_id, já que o Core admite várias partes acusadas por manifestação.
-- Descarta os vínculos antigos (dados de teste); os membros em `academic_members` permanecem.

DROP TABLE IF EXISTS manifestation_accusations;

CREATE TABLE manifestation_accusations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manifestation_id  BIGINT    NOT NULL,
    accused_party_id  BIGINT    NOT NULL,
    created_at        TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP NOT NULL,
    active            BOOLEAN   NOT NULL
);
