-- O cadastro de pessoas/unidades deixou de ser próprio da instância e passou a ser o registro
-- genérico do Core (br.imd.ufrn.core.domain.Party, tabela `parties`, endpoint /v1/parties).
-- Cria a tabela do Core e descarta a `academic_members` local (dados de teste).

CREATE TABLE parties (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    unit       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    active     BOOLEAN      NOT NULL
);

DROP TABLE IF EXISTS academic_members;
