-- Esquema de autenticação da Instância 2 (usuários e departamentos), espelhado da Instância 1.
-- Dado próprio da instância; o Core referencia analistas apenas por id (Long).

CREATE TABLE department (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    acronym    VARCHAR(30),
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    active     BOOLEAN      NOT NULL
);

CREATE TABLE user_info (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) UNIQUE,
    name          VARCHAR(255) NOT NULL,
    username      VARCHAR(255) NOT NULL UNIQUE,
    password      VARCHAR(255) NOT NULL,
    role          VARCHAR(255) NOT NULL,
    department_id BIGINT REFERENCES department (id),
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    active        BOOLEAN      NOT NULL
);
